"""added password_hash and confirmed columns

Revision ID: ce29343ebbb0
Revises: 4cd0be3445f0
Create Date: 2018-09-14 17:25:32.711948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce29343ebbb0'
down_revision = '4cd0be3445f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
